name: Sonic Union Music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34389
title: Home of DJ / Producer Sonic Union
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b2b2'
    - '#4c4c4c'
    - '#656565'
    - '#fefefe'
    - '#cbcbcb'
  brandStrength: 0.6958388665225357
  lightness: 0.04361248109489679
  saturation: 0.375
  rhythmicContrast: 0.3772320488933474
purpose: []
